name: CI

on:
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '19.x'

      - name: Install modules
        run: npm install

      - name: Run tests
        run: npm run test